Fix Rake task to fix answers for file upload answer with missing filename
This Rake task was failing in production with the error

```
NoMethodError: undefined method 'position' for nil (NoMethodError)
        filename = "#{question.position}-#{question.question_text.parameterize}#{extension}"
```

It turns out `Form#page_with_id` was assuming that the page ID was an
integer, however since PR #1727 steps (and hence pages) IDs can be
strings, and we've since migrated most form documents to use an
random alphanumeric string as the step ID.

This commit fixes `Form#page_with_id` to work with string IDs, and hence
fixes the `submissions:file_answers:fix_missing_original_filenames`
task.