Raise ArgumentError if Question::Date#assign_attributes is passed array
We were getting errors in production with the error message

```
undefined method 'transform_keys' for an instance of Array (NoMethodError)

      translated_attrs = new_attributes.transform_keys { |key| date_field_to_attribute(key) }
                                       ^^^^^^^^^^^^^^^
```

This was happening because a date question had been changed from "more
than one answer" to "only one answer", and the answer in the answer
store was an array, but we were assuming that `#assign_attributes` would
only ever be called with a hash.

Normally we catch this by looking for an ArgumentError exception, which
`ActiveModel::AttributeAssignment#assign_attributes` raises, but because
we were overloading that method we need to do the same check ourselves.
The error handling is copied pretty much verbatim from there [[1]].

[1]: https://github.com/rails/rails/blob/6406991804db6674ac511cfc14ce144a836f0712/activemodel/lib/active_model/attribute_assignment.rb#L29-L31